### ISSUE TITLE
Rename this projet to shopinvader-js-fetch

### ISSUE THREAD

**Issue by sbidoul** [shopinvader/shopinvader-js-fetch#5]
I propose to rename this GitHub project to `shopinvader-js-fetch`

- to match the package name (`@shopinvader/fetch`)
- to match the name pattern of `shopinvader-js-cart` which hosts `@shopinvader/cart`

@thibaultrey ok for you ?

**Comment by thibaultrey** [comment]
@sbidoul OK for me :)

**Comment by sbidoul** [comment]
done
